#!/bin/sh

Domain_viaVPN="
2ip.io
"
viaVPN="
104.19.222.79/32
104.19.223.79/32
"
### Custom user script
### Called after internal VPN client connected/disconnected to remote VPN server
### $1 - action (up/down)
## $IFNAME - tunnel interface name (e.g. ppp5 or tun0)
### $IPLOCAL - tunnel local IP address
### $IPREMOTE - tunnel remote IP address
### $DNS1 - peer DNS1
### $DNS2 - peer DNS2

# private LAN subnet behind a remote server (example)
#peer_lan="192.168.9.0"
#peer_msk="255.255.255.0"

### example: add static route to private LAN subnet behind a remote server

func_ipup()
{
# route add -net $peer_lan netmask $peer_msk gw $IPREMOTE dev $IFNAME
for IP in $viaVPN
do
ip route add $IP dev $IFNAME
done
touch /opt/home/admin/my_domain_via_Web.lst
echo $Domain_viaVPN > /opt/home/admin/my_domain_via_Web.lst
return 0
}

func_ipdown()
{
# route del -net $peer_lan netmask $peer_msk gw $IPREMOTE dev $IFNAME
for IP in $viaVPN
do
ip route del $IP dev $IFNAME
done
return 0
}

logger -t vpnc-script "$IFNAME $1"

case "$1" in
up)
logger -t vpnc-script "func up start"
func_ipup
/etc/storage/add_routes.sh&
logger -t vpnc-script "func up finish"
;;
down)
func_ipdown

logger -t vpnc-script "func down"

;;
esac
